name = input("Enter a name: ")
inspiration = input("Enter a person you admire: ")
hobby = input("Enter a hobby: ")
pizza = input("How many slices of pizza can you eat in one sitting?: ")
print(name + " is hard at work with " + hobby + ",")
print("when suddenly there was a knock at the door.")
print(name + " went to answer and to their surprise, it was " + inspiration + "!")
print("\"What's up " + name + "?\" They said.")
print("\"I knew you were hard at work on " + hobby + ", and thought I'd bring some pizza!\"")
print("Then " + name + " and " + inspiration + " hung out and ate pizza.")
print(name + " ate " + pizza + " slices, but " + inspiration + " ate 2000000000000000000000000000000000000000000000000000000000000000000000!")
